app:
  title: Toolbox Dev App
  baseUrl: http://localhost:3000

  toolbox:
    qrCode:
      defaults:
        dotType: rounded
        dotColor: 'blue'
        cornerSquareType: extra-rounded
        cornerSquareColor: 'blue'
        cornerDotType: dot
        cornerDotColor: 'blue'
        shape: square
    csr:
      defaults:
        country: 'AU'
        state: 'Victoria'
        locality: 'Melbourne'
        organization: 'Example Limited'

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    # client: better-sqlite3 # Use this if you don't have docker
    # connection: ':memory:'
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
    knexConfig:
      pool:
        min: 15
        max: 30
        acquireTimeoutMillis: 60000
        createTimeoutMillis: 30000
        destroyTimeoutMillis: 5000
        idleTimeoutMillis: 60000
        reapIntervalMillis: 1000
        createRetryIntervalMillis: 200
        propagateCreateError: false
  cache:
    store: memory
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  reading:
    allow:
      - host: localhost

